name: Docker Build And Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker image tag
      id: prep
      run: echo "IMAGE_TAG=${{ secrets.DOCKER_REGISTRY }}/be-quizbygpt:main-dev" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file BE.QuizByGPT/Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Log in to Docker Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: docker push ${{ env.IMAGE_TAG }}

    - name: Execute script on remote server
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/QuizByGPT/
          docker compose stop && docker compose rm && docker compose pull && docker compose up -d
