name: Docker Build And Push on

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - closed
    branches: [ "main" ]

jobs:
  if_merged:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker image tag
      id: prep
      run: echo "IMAGE_TAG=${{ secrets.DOCKER_REGISTRY }}/be-quizbygpt:$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file BE.QuizByGPT/Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Log in to Docker Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Image
      run: docker push ${{ env.IMAGE_TAG }}
